version: "3.8"
services:
  gitlab:
    image: registry.cn-hangzhou.aliyuncs.com/macroldj/gitlab-ce:17.11.7-ce.0
    container_name: gitlab
    hostname: gg-gitlab.example.com
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gg-gitlab.example.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab